# fly.toml app configuration file generated for simwrapper-api on 2023-12-10T22:48:39+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "simwrapper-api"
primary_region = "ams"

[build]

[[mounts]]
  source = "simwrapper_data"
  destination = "/data"
  auto_extend_size_threshold = 0

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
