# fly.toml app configuration file generated for vsp-cluster on 2024-10-18T17:53:42+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vsp-cluster'
primary_region = 'ams'

[build]

[[mounts]]
  source = 'simwrapper_data'
  destination = '/data'
  initial_size = '1gb'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
